// AUTO-GENERATED by Design Token System - DO NOT EDIT
// Edit tokens in tokens/ directory and run 'npm run build:tokens'

export const themeColors = {
  light: {
  "base": {
    "background": "#f5f5f5",
    "foreground": "#333333"
  },
  "card": {
    "default": "#ffffff",
    "foreground": "#333333",
    "border": "#e8d5c4",
    "hover": "#faf7f5"
  },
  "glass": {
    "bg": "rgba(255, 255, 255, 0.9)",
    "border": "rgba(226, 232, 240, 0.8)"
  },
  "popover": {
    "default": "#ffffff",
    "foreground": "#0a0a0a"
  },
  "modal": {
    "overlay": "rgba(0, 0, 0, 0.5)"
  },
  "primary": {
    "default": "#d6894a",
    "hover": "#c0773d",
    "foreground": "#ffffff",
    "muted": "rgba(214, 137, 74, 0.1)"
  },
  "secondary": {
    "default": "#f1f5f9",
    "hover": "#e2e8f0",
    "foreground": "#1e293b"
  },
  "accent": {
    "default": "#4a97d6",
    "hover": "#3d7eb8",
    "foreground": "#ffffff",
    "muted": "rgba(74, 151, 214, 0.1)"
  },
  "semantic": {
    "success": "#d6cf4a",
    "destructive": "#d64a51",
    "warning": "#d6894a"
  },
  "text": {
    "primary": "#333333",
    "secondary": "#6b5d54",
    "tertiary": "#8c7d73",
    "muted": "#aca399",
    "disabled": "#d8d3cd"
  },
  "border": {
    "default": "#e2e8f0",
    "subtle": "#f1f5f9",
    "strong": "#cbd5e1"
  },
  "input": {
    "default": "#ffffff",
    "border": "#cbd5e1",
    "foreground": "#0a0a0a",
    "placeholder": "#94a3b8",
    "disabled": "#f1f5f9"
  },
  "button": {
    "primary": {
      "bg": "#d6894a",
      "hover": "#c0773d",
      "active": "#aa6530",
      "text": "#ffffff"
    },
    "secondary": {
      "bg": "#f1f5f9",
      "hover": "#e2e8f0",
      "active": "#cbd5e1",
      "text": "#1e293b"
    },
    "ghost": {
      "hover": "#f1f5f9",
      "active": "#e2e8f0"
    },
    "outline": {
      "border": "#e2e8f0",
      "hover": {
        "bg": "#f8fafc"
      }
    }
  },
  "chart": {
    "1": "#d6894a",
    "2": "#a86f47",
    "3": "#e5a56e",
    "4": "#f59e0b",
    "5": "#ef4444",
    "6": "#10b981",
    "grid": "#e2e8f0",
    "axis": "#94a3b8",
    "label": "#64748b"
  },
  "polygon": {
    "fill": "rgba(214, 137, 74, 0.3)",
    "stroke": "#d6894a",
    "hover": {
      "fill": "rgba(214, 137, 74, 0.5)"
    },
    "selected": {
      "fill": "rgba(214, 137, 74, 0.7)",
      "stroke": "#c0773d"
    },
    "target": {
      "stroke": "#14b8a6",
      "fill": "rgba(20, 184, 166, 0.4)"
    },
    "neighbor": {
      "stroke": "#22c55e",
      "fill": "rgba(34, 197, 94, 0.3)"
    }
  },
  "mesh": {
    "ambient": "#ffffff",
    "directional": "#ffffff"
  },
  "map": {
    "base": "#faf7f5",
    "water": "#4a97d6",
    "land": "#f5f5f5",
    "border": "#e8d5c4",
    "label": "#6b5d54",
    "marker": "#d6894a"
  },
  "sidebar": {
    "default": "#ffffff",
    "foreground": "#0a0a0a",
    "primary": "#d6894a",
    "accent": "#f1f5f9",
    "border": "#e2e8f0",
    "ring": "#94a3b8"
  },
  "aurora": {
    "green": "#10b981",
    "cyan": "#06b6d4",
    "purple": "#8b5cf6",
    "pink": "#ec4899",
    "yellow": "#f59e0b",
    "red": "#ef4444",
    "blue": "#3b82f6",
    "glow": {
      "green": "rgba(16, 185, 129, 0.2)",
      "cyan": "rgba(6, 182, 212, 0.2)",
      "purple": "rgba(139, 92, 246, 0.2)"
    }
  }
},
  dark: {
  "base": {
    "background": "#0a0a0a",
    "foreground": "#fafafa"
  },
  "card": {
    "default": "#111111",
    "foreground": "#fafafa",
    "border": "#27272a",
    "hover": "#1a1a1a"
  },
  "glass": {
    "bg": "rgba(17, 17, 17, 0.5)",
    "border": "rgba(255, 255, 255, 0.1)"
  },
  "popover": {
    "default": "#111111",
    "foreground": "#fafafa"
  },
  "modal": {
    "overlay": "rgba(0, 0, 0, 0.8)"
  },
  "primary": {
    "default": "#10b981",
    "hover": "#34d399",
    "foreground": "#0a0a0a",
    "muted": "rgba(16, 185, 129, 0.15)"
  },
  "secondary": {
    "default": "#1a1a1a",
    "hover": "#27272a",
    "foreground": "#fafafa"
  },
  "accent": {
    "default": "#06b6d4",
    "hover": "#22d3ee",
    "foreground": "#0a0a0a",
    "muted": "rgba(6, 182, 212, 0.15)"
  },
  "semantic": {
    "success": "#10b981",
    "destructive": "#ef4444",
    "warning": "#f59e0b"
  },
  "text": {
    "primary": "#fafafa",
    "secondary": "#d4d4d8",
    "tertiary": "#a1a1aa",
    "muted": "#71717a",
    "disabled": "#52525b"
  },
  "border": {
    "default": "#27272a",
    "subtle": "#1a1a1a",
    "strong": "#3f3f46"
  },
  "input": {
    "default": "#1a1a1a",
    "border": "#3f3f46",
    "foreground": "#fafafa",
    "placeholder": "#71717a",
    "disabled": "#1a1a1a"
  },
  "button": {
    "primary": {
      "bg": "#10b981",
      "hover": "#34d399",
      "active": "#059669",
      "text": "#0a0a0a"
    },
    "secondary": {
      "bg": "#1a1a1a",
      "hover": "#27272a",
      "active": "#3f3f46",
      "text": "#fafafa"
    },
    "ghost": {
      "hover": "#1a1a1a",
      "active": "#27272a"
    },
    "outline": {
      "border": "#27272a",
      "hover": {
        "bg": "#111111"
      }
    }
  },
  "chart": {
    "1": "#10b981",
    "2": "#06b6d4",
    "3": "#8b5cf6",
    "4": "#f59e0b",
    "5": "#ef4444",
    "6": "#ec4899",
    "grid": "#27272a",
    "axis": "#52525b",
    "label": "#71717a"
  },
  "polygon": {
    "fill": "rgba(34, 197, 94, 0.3)",
    "stroke": "#22c55e",
    "hover": {
      "fill": "rgba(34, 197, 94, 0.5)"
    },
    "selected": {
      "fill": "rgba(236, 72, 153, 0.5)",
      "stroke": "#ec4899"
    },
    "target": {
      "stroke": "#ec4899",
      "fill": "rgba(236, 72, 153, 0.4)"
    },
    "neighbor": {
      "stroke": "#22c55e",
      "fill": "rgba(34, 197, 94, 0.3)"
    }
  },
  "mesh": {
    "ambient": "#1a1a1a",
    "directional": "#fafafa"
  },
  "map": {
    "base": "#52525b",
    "water": "#1e3a5f",
    "land": "#1a1a1a",
    "border": "#fafafa",
    "label": "#fafafa",
    "marker": "#22c55e"
  },
  "sidebar": {
    "default": "#111111",
    "foreground": "#fafafa",
    "primary": "#10b981",
    "accent": "#1a1a1a",
    "border": "#27272a",
    "ring": "#71717a"
  },
  "aurora": {
    "green": "#10b981",
    "cyan": "#06b6d4",
    "purple": "#8b5cf6",
    "pink": "#ec4899",
    "yellow": "#f59e0b",
    "red": "#ef4444",
    "blue": "#3b82f6",
    "glow": {
      "green": "rgba(16, 185, 129, 0.3)",
      "cyan": "rgba(6, 182, 212, 0.3)",
      "purple": "rgba(139, 92, 246, 0.3)"
    }
  }
}
} as const;

export type ThemeMode = 'light' | 'dark';
export type ThemeColors = typeof themeColors;

// Flat color maps for direct access (e.g., in Leaflet, Three.js)
export const flatColors = {
  light: {
  "base-background": "#f5f5f5",
  "base-background-elevated": "#ffffff",
  "base-background-subtle": "#faf7f5",
  "base-foreground": "#333333",
  "card-default": "#ffffff",
  "card-foreground": "#333333",
  "card-border": "#e8d5c4",
  "card-hover": "#faf7f5",
  "glass-bg": "rgba(255, 255, 255, 0.9)",
  "glass-border": "rgba(226, 232, 240, 0.8)",
  "popover-default": "#ffffff",
  "popover-foreground": "#0a0a0a",
  "modal-overlay": "rgba(0, 0, 0, 0.5)",
  "primary-default": "#d6894a",
  "primary-hover": "#c0773d",
  "primary-foreground": "#ffffff",
  "primary-muted": "rgba(214, 137, 74, 0.1)",
  "secondary-default": "#f1f5f9",
  "secondary-hover": "#e2e8f0",
  "secondary-foreground": "#1e293b",
  "accent-default": "#4a97d6",
  "accent-hover": "#3d7eb8",
  "accent-foreground": "#ffffff",
  "accent-muted": "rgba(74, 151, 214, 0.1)",
  "semantic-success": "#d6cf4a",
  "semantic-success-foreground": "#333333",
  "semantic-success-muted": "rgba(214, 207, 74, 0.1)",
  "semantic-destructive": "#d64a51",
  "semantic-destructive-hover": "#c03e44",
  "semantic-destructive-foreground": "#ffffff",
  "semantic-destructive-muted": "rgba(214, 74, 81, 0.1)",
  "semantic-warning": "#d6894a",
  "semantic-warning-foreground": "#ffffff",
  "semantic-warning-muted": "rgba(214, 137, 74, 0.1)",
  "text-primary": "#333333",
  "text-secondary": "#6b5d54",
  "text-tertiary": "#8c7d73",
  "text-muted": "#aca399",
  "text-disabled": "#d8d3cd",
  "border-default": "#e2e8f0",
  "border-subtle": "#f1f5f9",
  "border-strong": "#cbd5e1",
  "input-default": "#ffffff",
  "input-border": "#cbd5e1",
  "input-border-hover": "#94a3b8",
  "input-border-focus": "#d6894a",
  "input-foreground": "#0a0a0a",
  "input-placeholder": "#94a3b8",
  "input-disabled": "#f1f5f9",
  "button-primary-bg": "#d6894a",
  "button-primary-hover": "#c0773d",
  "button-primary-active": "#aa6530",
  "button-primary-text": "#ffffff",
  "button-secondary-bg": "#f1f5f9",
  "button-secondary-hover": "#e2e8f0",
  "button-secondary-active": "#cbd5e1",
  "button-secondary-text": "#1e293b",
  "button-ghost-hover": "#f1f5f9",
  "button-ghost-active": "#e2e8f0",
  "button-outline-border": "#e2e8f0",
  "button-outline-hover-bg": "#f8fafc",
  "chart-1": "#d6894a",
  "chart-2": "#a86f47",
  "chart-3": "#e5a56e",
  "chart-4": "#f59e0b",
  "chart-5": "#ef4444",
  "chart-6": "#10b981",
  "chart-grid": "#e2e8f0",
  "chart-axis": "#94a3b8",
  "chart-label": "#64748b",
  "polygon-fill": "rgba(214, 137, 74, 0.3)",
  "polygon-stroke": "#d6894a",
  "polygon-hover-fill": "rgba(214, 137, 74, 0.5)",
  "polygon-selected-fill": "rgba(214, 137, 74, 0.7)",
  "polygon-selected-stroke": "#c0773d",
  "polygon-target-stroke": "#14b8a6",
  "polygon-target-fill": "rgba(20, 184, 166, 0.4)",
  "polygon-neighbor-stroke": "#22c55e",
  "polygon-neighbor-fill": "rgba(34, 197, 94, 0.3)",
  "mesh-ambient": "#ffffff",
  "mesh-directional": "#ffffff",
  "map-base": "#faf7f5",
  "map-water": "#4a97d6",
  "map-land": "#f5f5f5",
  "map-border": "#e8d5c4",
  "map-label": "#6b5d54",
  "map-marker": "#d6894a",
  "map-marker-hover": "#c0773d",
  "sidebar-default": "#ffffff",
  "sidebar-foreground": "#0a0a0a",
  "sidebar-primary": "#d6894a",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-accent": "#f1f5f9",
  "sidebar-accent-foreground": "#1e293b",
  "sidebar-border": "#e2e8f0",
  "sidebar-ring": "#94a3b8",
  "aurora-green": "#10b981",
  "aurora-cyan": "#06b6d4",
  "aurora-purple": "#8b5cf6",
  "aurora-pink": "#ec4899",
  "aurora-yellow": "#f59e0b",
  "aurora-red": "#ef4444",
  "aurora-blue": "#3b82f6",
  "aurora-glow-green": "rgba(16, 185, 129, 0.2)",
  "aurora-glow-cyan": "rgba(6, 182, 212, 0.2)",
  "aurora-glow-purple": "rgba(139, 92, 246, 0.2)"
},
  dark: {
  "base-background": "#0a0a0a",
  "base-background-elevated": "#111111",
  "base-background-subtle": "#1a1a1a",
  "base-foreground": "#fafafa",
  "card-default": "#111111",
  "card-foreground": "#fafafa",
  "card-border": "#27272a",
  "card-hover": "#1a1a1a",
  "glass-bg": "rgba(17, 17, 17, 0.5)",
  "glass-border": "rgba(255, 255, 255, 0.1)",
  "popover-default": "#111111",
  "popover-foreground": "#fafafa",
  "modal-overlay": "rgba(0, 0, 0, 0.8)",
  "primary-default": "#10b981",
  "primary-hover": "#34d399",
  "primary-foreground": "#0a0a0a",
  "primary-muted": "rgba(16, 185, 129, 0.15)",
  "secondary-default": "#1a1a1a",
  "secondary-hover": "#27272a",
  "secondary-foreground": "#fafafa",
  "accent-default": "#06b6d4",
  "accent-hover": "#22d3ee",
  "accent-foreground": "#0a0a0a",
  "accent-muted": "rgba(6, 182, 212, 0.15)",
  "semantic-success": "#10b981",
  "semantic-success-foreground": "#0a0a0a",
  "semantic-success-muted": "rgba(16, 185, 129, 0.15)",
  "semantic-destructive": "#ef4444",
  "semantic-destructive-hover": "#f87171",
  "semantic-destructive-foreground": "#fafafa",
  "semantic-destructive-muted": "rgba(239, 68, 68, 0.15)",
  "semantic-warning": "#f59e0b",
  "semantic-warning-foreground": "#0a0a0a",
  "semantic-warning-muted": "rgba(245, 158, 11, 0.15)",
  "text-primary": "#fafafa",
  "text-secondary": "#d4d4d8",
  "text-tertiary": "#a1a1aa",
  "text-muted": "#71717a",
  "text-disabled": "#52525b",
  "border-default": "#27272a",
  "border-subtle": "#1a1a1a",
  "border-strong": "#3f3f46",
  "input-default": "#1a1a1a",
  "input-border": "#3f3f46",
  "input-border-hover": "#52525b",
  "input-border-focus": "#10b981",
  "input-foreground": "#fafafa",
  "input-placeholder": "#71717a",
  "input-disabled": "#1a1a1a",
  "button-primary-bg": "#10b981",
  "button-primary-hover": "#34d399",
  "button-primary-active": "#059669",
  "button-primary-text": "#0a0a0a",
  "button-secondary-bg": "#1a1a1a",
  "button-secondary-hover": "#27272a",
  "button-secondary-active": "#3f3f46",
  "button-secondary-text": "#fafafa",
  "button-ghost-hover": "#1a1a1a",
  "button-ghost-active": "#27272a",
  "button-outline-border": "#27272a",
  "button-outline-hover-bg": "#111111",
  "chart-1": "#10b981",
  "chart-2": "#06b6d4",
  "chart-3": "#8b5cf6",
  "chart-4": "#f59e0b",
  "chart-5": "#ef4444",
  "chart-6": "#ec4899",
  "chart-grid": "#27272a",
  "chart-axis": "#52525b",
  "chart-label": "#71717a",
  "polygon-fill": "rgba(34, 197, 94, 0.3)",
  "polygon-stroke": "#22c55e",
  "polygon-hover-fill": "rgba(34, 197, 94, 0.5)",
  "polygon-selected-fill": "rgba(236, 72, 153, 0.5)",
  "polygon-selected-stroke": "#ec4899",
  "polygon-target-stroke": "#ec4899",
  "polygon-target-fill": "rgba(236, 72, 153, 0.4)",
  "polygon-neighbor-stroke": "#22c55e",
  "polygon-neighbor-fill": "rgba(34, 197, 94, 0.3)",
  "mesh-ambient": "#1a1a1a",
  "mesh-directional": "#fafafa",
  "map-base": "#52525b",
  "map-water": "#1e3a5f",
  "map-land": "#1a1a1a",
  "map-border": "#fafafa",
  "map-label": "#fafafa",
  "map-marker": "#22c55e",
  "map-marker-hover": "#4ade80",
  "map-marker-selected": "#ec4899",
  "map-marker-selected-hover": "#f472b6",
  "sidebar-default": "#111111",
  "sidebar-foreground": "#fafafa",
  "sidebar-primary": "#10b981",
  "sidebar-primary-foreground": "#0a0a0a",
  "sidebar-accent": "#1a1a1a",
  "sidebar-accent-foreground": "#fafafa",
  "sidebar-border": "#27272a",
  "sidebar-ring": "#71717a",
  "aurora-green": "#10b981",
  "aurora-cyan": "#06b6d4",
  "aurora-purple": "#8b5cf6",
  "aurora-pink": "#ec4899",
  "aurora-yellow": "#f59e0b",
  "aurora-red": "#ef4444",
  "aurora-blue": "#3b82f6",
  "aurora-glow-green": "rgba(16, 185, 129, 0.3)",
  "aurora-glow-cyan": "rgba(6, 182, 212, 0.3)",
  "aurora-glow-purple": "rgba(139, 92, 246, 0.3)"
}
} as const;

// Helper to get color value by dot-notation path
export function getColorValue(
  mode: ThemeMode,
  path: string
): string {
  const parts = path.split('.');
  let current: any = themeColors[mode];

  for (const part of parts) {
    if (current && typeof current === 'object' && part in current) {
      current = current[part];
    } else {
      return '';
    }
  }

  return typeof current === 'string' ? current : '';
}

// Helper to get flat color by key
export function getFlatColor(mode: ThemeMode, key: string): string {
  return flatColors[mode][key as keyof typeof flatColors[typeof mode]] || '';
}
