const StyleDictionary = require('style-dictionary');

// Custom format for CSS variables
StyleDictionary.registerFormat({
  name: 'css/variables-themes',
  formatter: function({ dictionary, options }) {
    const { mode } = options;

    // Helper to convert token path to CSS variable name
    const getVarName = (path) => {
      // Remove 'color.light' or 'color.dark' prefix
      const cleanPath = path.filter(p => p !== 'color' && p !== mode);
      return `--${cleanPath.join('-')}`;
    };

    // Helper to check if token belongs to current mode
    const isTokenForMode = (token) => {
      return token.path.includes(mode);
    };

    const tokens = dictionary.allTokens
      .filter(isTokenForMode)
      .map(token => {
        const varName = getVarName(token.path);
        return `  ${varName}: ${token.value};`;
      })
      .join('\n');

    if (mode === 'light') {
      return `:root {\n  --radius: 0.625rem;\n\n  /* ============================================\n     LIGHT MODE - DESIGN TOKEN SYSTEM\n     ============================================ */\n\n${tokens}\n}\n`;
    } else {
      return `.dark {\n  /* ============================================\n     DARK MODE - DESIGN TOKEN SYSTEM\n     ============================================ */\n\n${tokens}\n}\n`;
    }
  }
});

// Custom format for TypeScript
StyleDictionary.registerFormat({
  name: 'typescript/theme-colors',
  formatter: function({ dictionary }) {
    const buildColorObject = (tokens, mode) => {
      const obj = {};
      tokens
        .filter(token => token.path.includes(mode))
        .forEach(token => {
          const path = token.path.filter(p => p !== 'color' && p !== mode);
          let current = obj;

          for (let i = 0; i < path.length - 1; i++) {
            const key = path[i];
            if (!current[key]) current[key] = {};
            current = current[key];
          }

          const lastKey = path[path.length - 1];
          current[lastKey] = token.value;
        });
      return obj;
    };

    const lightColors = buildColorObject(dictionary.allTokens, 'light');
    const darkColors = buildColorObject(dictionary.allTokens, 'dark');

    return `// AUTO-GENERATED by Style Dictionary - DO NOT EDIT
// Edit tokens in tokens/ directory and run 'npm run build:tokens'

export const themeColors = {
  light: ${JSON.stringify(lightColors, null, 2)},
  dark: ${JSON.stringify(darkColors, null, 2)}
} as const;

export type ThemeMode = 'light' | 'dark';
export type ThemeColors = typeof themeColors;

// Helper to get color value by path
export function getColorValue(
  mode: ThemeMode,
  path: string
): string {
  const parts = path.split('.');
  let current: any = themeColors[mode];

  for (const part of parts) {
    if (current && typeof current === 'object' && part in current) {
      current = current[part];
    } else {
      return '';
    }
  }

  return typeof current === 'string' ? current : '';
}
`;
  }
});

module.exports = {
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'src/app/',
      files: [
        {
          destination: 'globals-generated.css',
          format: 'css/variables-themes',
          options: {
            mode: 'light'
          }
        },
        {
          destination: 'globals-generated.css',
          format: 'css/variables-themes',
          options: {
            mode: 'dark',
            append: true
          }
        }
      ]
    },
    ts: {
      transformGroup: 'js',
      buildPath: 'src/lib/',
      files: [
        {
          destination: 'theme-colors.ts',
          format: 'typescript/theme-colors'
        }
      ]
    }
  }
};
