const fs = require('fs');
const path = require('path');

// Load token files
const lightTokens = require('../tokens/colors/light.json');
const darkTokens = require('../tokens/colors/dark.json');
const coreTokens = require('../tokens/core/common.json');

// Helper to flatten nested token structure
function flattenTokens(obj, prefix = '', mode = '') {
  let result = {};

  for (const [key, value] of Object.entries(obj)) {
    const newPrefix = prefix ? `${prefix}-${key}` : key;

    if (value && typeof value === 'object' && 'value' in value) {
      // This is a token with a value
      result[newPrefix] = value.value;
    } else if (value && typeof value === 'object') {
      // This is a nested object, recurse
      Object.assign(result, flattenTokens(value, newPrefix, mode));
    }
  }

  return result;
}

// Map token names to CSS variable names that match Tailwind config
function mapTokenName(tokenName) {
  // Map base-background -> background
  if (tokenName.startsWith('base-')) {
    return tokenName.replace('base-', '');
  }
  // Map primary-default -> primary
  if (tokenName.match(/^(primary|secondary|accent|popover|card)-default$/)) {
    return tokenName.replace('-default', '');
  }
  // Map semantic-success -> success
  if (tokenName.startsWith('semantic-')) {
    return tokenName.replace('semantic-', '');
  }
  return tokenName;
}

// Generate CSS variables
function generateCSS() {
  // Flatten light mode tokens
  const lightFlat = flattenTokens(lightTokens.color.light);

  // Flatten dark mode tokens
  const darkFlat = flattenTokens(darkTokens.color.dark);

  // Flatten core tokens
  const coreFlat = flattenTokens(coreTokens);

  let css = `/* ============================================
   AUTO-GENERATED by Design Token System
   DO NOT EDIT - Edit tokens in tokens/ directory
   Run 'npm run build:tokens' to regenerate
   ============================================ */

@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --radius: 0.625rem;

  /* ============================================
     LIGHT MODE - DESIGN TOKEN SYSTEM
     ============================================ */

`;

  // Add light mode variables
  Object.entries(lightFlat).forEach(([key, value]) => {
    const mappedKey = mapTokenName(key);
    css += `  --${mappedKey}: ${value};\n`;
  });

  // Add core light mode variables
  Object.entries(coreFlat).forEach(([key, value]) => {
    if (key.includes('light')) {
      const cleanKey = key.replace(/-(light|dark)$/, '');
      if (key.endsWith('-light')) {
        css += `  --${cleanKey}: ${value};\n`;
      }
    }
  });

  // Add gradients
  if (coreTokens.gradient && coreTokens.gradient.light) {
    Object.entries(coreTokens.gradient.light).forEach(([key, config]) => {
      css += `  --gradient-${key}: ${config.value};\n`;
    });
  }

  // Add shadows
  if (coreTokens.shadow && coreTokens.shadow.light) {
    Object.entries(coreTokens.shadow.light).forEach(([key, config]) => {
      css += `  --shadow-${key}: ${config.value};\n`;
    });
  }

  css += `}\n\n.dark {\n  /* ============================================\n     DARK MODE - DESIGN TOKEN SYSTEM\n     ============================================ */\n\n`;

  // Add dark mode variables
  Object.entries(darkFlat).forEach(([key, value]) => {
    const mappedKey = mapTokenName(key);
    css += `  --${mappedKey}: ${value};\n`;
  });

  // Add core dark mode variables
  Object.entries(coreFlat).forEach(([key, value]) => {
    if (key.includes('dark')) {
      const cleanKey = key.replace(/-(light|dark)$/, '');
      if (key.endsWith('-dark')) {
        css += `  --${cleanKey}: ${value};\n`;
      }
    }
  });

  // Add dark gradients
  if (coreTokens.gradient && coreTokens.gradient.dark) {
    Object.entries(coreTokens.gradient.dark).forEach(([key, config]) => {
      css += `  --gradient-${key}: ${config.value};\n`;
    });
  }

  // Add dark shadows
  if (coreTokens.shadow && coreTokens.shadow.dark) {
    Object.entries(coreTokens.shadow.dark).forEach(([key, config]) => {
      css += `  --shadow-${key}: ${config.value};\n`;
    });
  }

  css += `}\n\n@layer base {
  * {
    @apply border-border;
  }
  *:focus-visible {
    @apply outline-ring;
  }
  body {
    @apply bg-background text-foreground;
  }
}
`;

  return css;
}

// Generate TypeScript file
function generateTypeScript() {
  const lightFlat = flattenTokens(lightTokens.color.light);
  const darkFlat = flattenTokens(darkTokens.color.dark);

  // Build nested objects for better TypeScript experience
  const buildNestedObject = (flat) => {
    const result = {};
    Object.entries(flat).forEach(([key, value]) => {
      const parts = key.split('-');
      let current = result;

      for (let i = 0; i < parts.length - 1; i++) {
        const part = parts[i];
        if (!current[part]) current[part] = {};
        // Ensure current[part] is an object before continuing
        if (typeof current[part] !== 'object' || current[part] === null) {
          // If we're trying to nest into a string value, skip this path
          console.warn(`Warning: Cannot nest into non-object at key "${parts.slice(0, i + 1).join('-')}" - skipping "${key}"`);
          return;
        }
        current = current[part];
      }

      const lastPart = parts[parts.length - 1];
      // Only set if current is still an object
      if (typeof current === 'object' && current !== null) {
        current[lastPart] = value;
      }
    });
    return result;
  };

  const lightNested = buildNestedObject(lightFlat);
  const darkNested = buildNestedObject(darkFlat);

  return `// AUTO-GENERATED by Design Token System - DO NOT EDIT
// Edit tokens in tokens/ directory and run 'npm run build:tokens'

export const themeColors = {
  light: ${JSON.stringify(lightNested, null, 2)},
  dark: ${JSON.stringify(darkNested, null, 2)}
} as const;

export type ThemeMode = 'light' | 'dark';
export type ThemeColors = typeof themeColors;

// Flat color maps for direct access (e.g., in Leaflet, Three.js)
export const flatColors = {
  light: ${JSON.stringify(lightFlat, null, 2)},
  dark: ${JSON.stringify(darkFlat, null, 2)}
} as const;

// Helper to get color value by dot-notation path
export function getColorValue(
  mode: ThemeMode,
  path: string
): string {
  const parts = path.split('.');
  let current: any = themeColors[mode];

  for (const part of parts) {
    if (current && typeof current === 'object' && part in current) {
      current = current[part];
    } else {
      return '';
    }
  }

  return typeof current === 'string' ? current : '';
}

// Helper to get flat color by key
export function getFlatColor(mode: ThemeMode, key: string): string {
  return flatColors[mode][key as keyof typeof flatColors[typeof mode]] || '';
}
`;
}

// Main build function
function build() {
  console.log('🎨 Building design tokens...\n');

  // Generate CSS
  console.log('📝 Generating globals.css...');
  const css = generateCSS();
  fs.writeFileSync(
    path.join(__dirname, '../src/app/globals.css'),
    css,
    'utf-8'
  );
  console.log('✅ globals.css generated\n');

  // Generate TypeScript
  console.log('📝 Generating theme-colors.ts...');
  const ts = generateTypeScript();
  fs.mkdirSync(path.join(__dirname, '../src/lib'), { recursive: true });
  fs.writeFileSync(
    path.join(__dirname, '../src/lib/theme-colors.ts'),
    ts,
    'utf-8'
  );
  console.log('✅ theme-colors.ts generated\n');

  console.log('🎉 Design tokens build complete!');
  console.log('   - Edit tokens in: tokens/ directory');
  console.log('   - CSS output: src/app/globals.css');
  console.log('   - TypeScript: src/lib/theme-colors.ts');
}

// Run build
build();
